on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
    - run : node --version
    - run : npm --version
    - uses: actions/checkout@v3 
    - run: npm install
    - run : node app.js

      
    - name: Build Docker image
        working-directory: Docker-image 
        run: docker build . --Dockerfile --tag node-docker:(date +%s)
    

