on: push

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
    - run : node --version
    - run : npm --version
    - uses: actions/checkout@v3 
    - run: npm install
    - run : node app.js
    - run: |
          docker build -t my-node-app:${{ github.sha }} .
          docker tag my-node-app:${{ github.sha }} my-registry.com/my-node-app:${{ github.sha }}

